openapi: 3.0.0
info:
  version: 1.0.0
  title: Authentication API
  description: Endpoints related to user authentication and registration

paths:
  /auth/register:
    post:
      tags:
      - Authentication
      summary: Register a new user
      requestBody:
        description: User details to register a new user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
                role:
                  type: string
                  enum:
                  - maker
                  - approver
                  - admin
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: Invalid input or user already exists

  /auth/login:
    post:
      tags:
      - Authentication
      summary: User login
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      role:
                        type: string
                        enum:
                        - maker
                        - approver
                        - admin
        401:
          description: Unauthorized or invalid credentials
        500:
          description: Server error

