openapi: 3.0.0
info:
  version: 1.0.0
  title: History API
  description: Endpoints related to transfer request history

paths:
  /history:
    get:
      tags:
      - History
      summary: Get transfer request history
      parameters:
      - name: startDate
        in: query
        description: Starting date for the history filter
        required: false
        schema:
          type: string
          format: date
      - name: endDate
        in: query
        description: Ending date for the history filter
        required: false
        schema:
          type: string
          format: date
      - name: status
        in: query
        description: Status filter for the history, can be multiple
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - pending
            - approved
            - rejected
            - done
      security:
      - ApiKeyAuth: []
      responses:
        200:
          description: Transfer request history fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    createdBy:
                      type: string
                    approvedBy:
                      type: string
                    status:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
        401:
          description: Unauthorized
        500:
          description: Server error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
